<?php
namespace PHPMaker2020\sigap;

// Menu Language
if ($Language && function_exists(PROJECT_NAMESPACE . "Config") && $Language->LanguageFolder == Config("LANGUAGE_FOLDER")) {
	$MenuRelativePath = "";
	$MenuLanguage = &$Language;
} else { // Compat reports
	$LANGUAGE_FOLDER = "../lang/";
	$MenuRelativePath = "../";
	$MenuLanguage = new Language();
}

// Navbar menu
$topMenu = new Menu("navbar", TRUE, TRUE);
echo $topMenu->toScript();

// Sidebar menu
$sideMenu = new Menu("menu", TRUE, FALSE);
$sideMenu->addMenuItem(40, "mi_pegawai", $MenuLanguage->MenuPhrase("40", "MenuText"), $MenuRelativePath . "pegawailist.php", -1, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}pegawai'), FALSE, FALSE, "fa fa-user", "", FALSE);
$sideMenu->addMenuItem(1, "mi_absen", $MenuLanguage->MenuPhrase("1", "MenuText"), $MenuRelativePath . "absenlist.php", -1, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}absen'), FALSE, FALSE, "fa fa-clock-o", "", FALSE);
$sideMenu->addMenuItem(163, "mci_Unit_TK", $MenuLanguage->MenuPhrase("163", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fas fa-school", "", FALSE);
$sideMenu->addMenuItem(250, "mi_potongan_tk", $MenuLanguage->MenuPhrase("250", "MenuText"), $MenuRelativePath . "potongan_tklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}potongan_tk'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(258, "mi_m_tk", $MenuLanguage->MenuPhrase("258", "MenuText"), $MenuRelativePath . "m_tklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tk'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(259, "mi_m_tu_tk", $MenuLanguage->MenuPhrase("259", "MenuText"), $MenuRelativePath . "m_tu_tklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tu_tk'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(257, "mi_m_karyawan_tk", $MenuLanguage->MenuPhrase("257", "MenuText"), $MenuRelativePath . "m_karyawan_tklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_karyawan_tk'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(233, "mi_v_totalgajitk", $MenuLanguage->MenuPhrase("233", "MenuText"), $MenuRelativePath . "v_totalgajitklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajitk'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(234, "mi_v_totalgajitutk", $MenuLanguage->MenuPhrase("234", "MenuText"), $MenuRelativePath . "v_totalgajitutklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajitutk'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(235, "mi_v_totalgajikaryawantk", $MenuLanguage->MenuPhrase("235", "MenuText"), $MenuRelativePath . "v_totalgajikaryawantklist.php", 163, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajikaryawantk'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(223, "mci_Unit_SD", $MenuLanguage->MenuPhrase("223", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fas fa-school", "", FALSE);
$sideMenu->addMenuItem(44, "mi_potongan_sd", $MenuLanguage->MenuPhrase("44", "MenuText"), $MenuRelativePath . "potongan_sdlist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}potongan_sd'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(261, "mi_m_sd", $MenuLanguage->MenuPhrase("261", "MenuText"), $MenuRelativePath . "m_sdlist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_sd'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(262, "mi_m_tu_sd", $MenuLanguage->MenuPhrase("262", "MenuText"), $MenuRelativePath . "m_tu_sdlist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tu_sd'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(260, "mi_m_karyawan_sd", $MenuLanguage->MenuPhrase("260", "MenuText"), $MenuRelativePath . "m_karyawan_sdlist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_karyawan_sd'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(165, "mi_v_totalgaji", $MenuLanguage->MenuPhrase("165", "MenuText"), $MenuRelativePath . "v_totalgajilist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgaji'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(228, "mi_v_totalgajitu", $MenuLanguage->MenuPhrase("228", "MenuText"), $MenuRelativePath . "v_totalgajitulist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajitu'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(229, "mi_v_totalgajikaryawan", $MenuLanguage->MenuPhrase("229", "MenuText"), $MenuRelativePath . "v_totalgajikaryawanlist.php", 223, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajikaryawan'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(224, "mci_Unit_SMP", $MenuLanguage->MenuPhrase("224", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fas fa-school", "", FALSE);
$sideMenu->addMenuItem(45, "mi_potongan_smp", $MenuLanguage->MenuPhrase("45", "MenuText"), $MenuRelativePath . "potongan_smplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}potongan_smp'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(268, "mi_m_smp", $MenuLanguage->MenuPhrase("268", "MenuText"), $MenuRelativePath . "m_smplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_smp'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(265, "mi_m_karyawan_smp", $MenuLanguage->MenuPhrase("265", "MenuText"), $MenuRelativePath . "m_karyawan_smplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_karyawan_smp'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(271, "mi_m_tu_smp", $MenuLanguage->MenuPhrase("271", "MenuText"), $MenuRelativePath . "m_tu_smplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tu_smp'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(239, "mi_v_totalgajismp", $MenuLanguage->MenuPhrase("239", "MenuText"), $MenuRelativePath . "v_totalgajismplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajismp'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(240, "mi_v_totalgajitusmp", $MenuLanguage->MenuPhrase("240", "MenuText"), $MenuRelativePath . "v_totalgajitusmplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajitusmp'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(241, "mi_v_totalgajikaryawansmp", $MenuLanguage->MenuPhrase("241", "MenuText"), $MenuRelativePath . "v_totalgajikaryawansmplist.php", 224, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajikaryawansmp'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(164, "mci_Unit_SMA", $MenuLanguage->MenuPhrase("164", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fas fa-school", "", FALSE);
$sideMenu->addMenuItem(248, "mi_potongan_sma", $MenuLanguage->MenuPhrase("248", "MenuText"), $MenuRelativePath . "potongan_smalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}potongan_sma'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(266, "mi_m_sma", $MenuLanguage->MenuPhrase("266", "MenuText"), $MenuRelativePath . "m_smalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_sma'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(269, "mi_m_tu_sma", $MenuLanguage->MenuPhrase("269", "MenuText"), $MenuRelativePath . "m_tu_smalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tu_sma'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(263, "mi_m_karyawan_sma", $MenuLanguage->MenuPhrase("263", "MenuText"), $MenuRelativePath . "m_karyawan_smalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_karyawan_sma'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(251, "mi_v_totalgajisma", $MenuLanguage->MenuPhrase("251", "MenuText"), $MenuRelativePath . "v_totalgajismalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajisma'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(252, "mi_v_totalgajitusma", $MenuLanguage->MenuPhrase("252", "MenuText"), $MenuRelativePath . "v_totalgajitusmalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajitusma'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(253, "mi_v_totalgajikaryawansma", $MenuLanguage->MenuPhrase("253", "MenuText"), $MenuRelativePath . "v_totalgajikaryawansmalist.php", 164, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajikaryawansma'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(225, "mci_Unit_SMK", $MenuLanguage->MenuPhrase("225", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fas fa-school", "", FALSE);
$sideMenu->addMenuItem(249, "mi_potongan_smk", $MenuLanguage->MenuPhrase("249", "MenuText"), $MenuRelativePath . "potongan_smklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}potongan_smk'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(267, "mi_m_smk", $MenuLanguage->MenuPhrase("267", "MenuText"), $MenuRelativePath . "m_smklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_smk'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(270, "mi_m_tu_smk", $MenuLanguage->MenuPhrase("270", "MenuText"), $MenuRelativePath . "m_tu_smklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tu_smk'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(264, "mi_m_karyawan_smk", $MenuLanguage->MenuPhrase("264", "MenuText"), $MenuRelativePath . "m_karyawan_smklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_karyawan_smk'), FALSE, FALSE, "fa fa-credit-card", "", FALSE);
$sideMenu->addMenuItem(254, "mi_v_totalgajismk", $MenuLanguage->MenuPhrase("254", "MenuText"), $MenuRelativePath . "v_totalgajismklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajismk'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(255, "mi_v_totalgajitusmk", $MenuLanguage->MenuPhrase("255", "MenuText"), $MenuRelativePath . "v_totalgajitusmklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajitusmk'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(256, "mi_v_totalgajikaryawansmk", $MenuLanguage->MenuPhrase("256", "MenuText"), $MenuRelativePath . "v_totalgajikaryawansmklist.php", 225, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}v_totalgajikaryawansmk'), FALSE, FALSE, "fa fa-calculator", "", FALSE);
$sideMenu->addMenuItem(119, "mci_Keperluan_Pegawai", $MenuLanguage->MenuPhrase("119", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fas fa-users", "", FALSE);
$sideMenu->addMenuItem(24, "mi_ijin", $MenuLanguage->MenuPhrase("24", "MenuText"), $MenuRelativePath . "ijinlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}ijin'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(5, "mi_berita", $MenuLanguage->MenuPhrase("5", "MenuText"), $MenuRelativePath . "beritalist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}berita'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(32, "mi_komentar", $MenuLanguage->MenuPhrase("32", "MenuText"), $MenuRelativePath . "komentarlist.php?cmd=resetall", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}komentar'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(8, "mi_dinasluar", $MenuLanguage->MenuPhrase("8", "MenuText"), $MenuRelativePath . "dinasluarlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}dinasluar'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(48, "mi_terlambat", $MenuLanguage->MenuPhrase("48", "MenuText"), $MenuRelativePath . "terlambatlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}terlambat'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(33, "mi_lembur", $MenuLanguage->MenuPhrase("33", "MenuText"), $MenuRelativePath . "lemburlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}lembur'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(41, "mi_penempatan", $MenuLanguage->MenuPhrase("41", "MenuText"), $MenuRelativePath . "penempatanlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}penempatan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(42, "mi_pengetahuan", $MenuLanguage->MenuPhrase("42", "MenuText"), $MenuRelativePath . "pengetahuanlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}pengetahuan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(47, "mi_reimbursh", $MenuLanguage->MenuPhrase("47", "MenuText"), $MenuRelativePath . "reimburshlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}reimbursh'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(52, "mi_uangmuka", $MenuLanguage->MenuPhrase("52", "MenuText"), $MenuRelativePath . "uangmukalist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}uangmuka'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(7, "mi_daftarbarang", $MenuLanguage->MenuPhrase("7", "MenuText"), $MenuRelativePath . "daftarbaranglist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}daftarbarang'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(51, "mi_tpendidikan", $MenuLanguage->MenuPhrase("51", "MenuText"), $MenuRelativePath . "tpendidikanlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}tpendidikan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(10, "mi_gaji_pokok", $MenuLanguage->MenuPhrase("10", "MenuText"), $MenuRelativePath . "gaji_pokoklist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}gaji_pokok'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(25, "mi_jabatan", $MenuLanguage->MenuPhrase("25", "MenuText"), $MenuRelativePath . "jabatanlist.php", 119, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jabatan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(56, "mci_Master_Data", $MenuLanguage->MenuPhrase("56", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fa fa-database", "", FALSE);
$sideMenu->addMenuItem(46, "mi_proyek", $MenuLanguage->MenuPhrase("46", "MenuText"), $MenuRelativePath . "proyeklist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}proyek'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(55, "mi_setuju", $MenuLanguage->MenuPhrase("55", "MenuText"), $MenuRelativePath . "setujulist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}setuju'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(23, "mi_ijazah", $MenuLanguage->MenuPhrase("23", "MenuText"), $MenuRelativePath . "ijazahlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}ijazah'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(26, "mi_jenis_barang", $MenuLanguage->MenuPhrase("26", "MenuText"), $MenuRelativePath . "jenis_baranglist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_barang'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(29, "mi_jenis_grup_ilmu", $MenuLanguage->MenuPhrase("29", "MenuText"), $MenuRelativePath . "jenis_grup_ilmulist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_grup_ilmu'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(22, "mi_gender", $MenuLanguage->MenuPhrase("22", "MenuText"), $MenuRelativePath . "genderlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}gender'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(30, "mi_jenis_ijin", $MenuLanguage->MenuPhrase("30", "MenuText"), $MenuRelativePath . "jenis_ijinlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_ijin'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(31, "mi_jenis_lembur", $MenuLanguage->MenuPhrase("31", "MenuText"), $MenuRelativePath . "jenis_lemburlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_lembur'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(6, "mi_bulan", $MenuLanguage->MenuPhrase("6", "MenuText"), $MenuRelativePath . "bulanlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}bulan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(3, "mi_agama", $MenuLanguage->MenuPhrase("3", "MenuText"), $MenuRelativePath . "agamalist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}agama'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(28, "mi_jenis_grup_berita", $MenuLanguage->MenuPhrase("28", "MenuText"), $MenuRelativePath . "jenis_grup_beritalist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_grup_berita'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(27, "mi_jenis_dinasluar", $MenuLanguage->MenuPhrase("27", "MenuText"), $MenuRelativePath . "jenis_dinasluarlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_dinasluar'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(36, "mi_m_tidakhadir", $MenuLanguage->MenuPhrase("36", "MenuText"), $MenuRelativePath . "m_tidakhadirlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_tidakhadir'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(35, "mi_m_sakit", $MenuLanguage->MenuPhrase("35", "MenuText"), $MenuRelativePath . "m_sakitlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_sakit'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(34, "mi_m_pulangcepat", $MenuLanguage->MenuPhrase("34", "MenuText"), $MenuRelativePath . "m_pulangcepatlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_pulangcepat'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(120, "mi_mpendidikan", $MenuLanguage->MenuPhrase("120", "MenuText"), $MenuRelativePath . "mpendidikanlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}mpendidikan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(273, "mi_jenis_jabatan", $MenuLanguage->MenuPhrase("273", "MenuText"), $MenuRelativePath . "jenis_jabatanlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}jenis_jabatan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(272, "mi_tunjangan_tambahan", $MenuLanguage->MenuPhrase("272", "MenuText"), $MenuRelativePath . "tunjangan_tambahanlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}tunjangan_tambahan'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(274, "mi_tunjangan_berkala", $MenuLanguage->MenuPhrase("274", "MenuText"), $MenuRelativePath . "tunjangan_berkalalist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}tunjangan_berkala'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(276, "mi_m_kehadiran", $MenuLanguage->MenuPhrase("276", "MenuText"), $MenuRelativePath . "m_kehadiranlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_kehadiran'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(277, "mi_gaji_pokok_tu", $MenuLanguage->MenuPhrase("277", "MenuText"), $MenuRelativePath . "gaji_pokok_tulist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}gaji_pokok_tu'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(278, "mi_sertif", $MenuLanguage->MenuPhrase("278", "MenuText"), $MenuRelativePath . "sertiflist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}sertif'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(279, "mi_tambahan_tugas", $MenuLanguage->MenuPhrase("279", "MenuText"), $MenuRelativePath . "tambahan_tugaslist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}tambahan_tugas'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(280, "mi_m_piket", $MenuLanguage->MenuPhrase("280", "MenuText"), $MenuRelativePath . "m_piketlist.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}m_piket'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(281, "mi_test_api", $MenuLanguage->MenuPhrase("281", "MenuText"), $MenuRelativePath . "test_api.php", 56, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}test_api.php'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(57, "mci_Setting", $MenuLanguage->MenuPhrase("57", "MenuText"), "", -1, "", IsLoggedIn(), FALSE, TRUE, "fa fa-cog", "", FALSE);
$sideMenu->addMenuItem(4, "mi_audittrail", $MenuLanguage->MenuPhrase("4", "MenuText"), $MenuRelativePath . "audittraillist.php", 57, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}audittrail'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(54, "mi_userlevels", $MenuLanguage->MenuPhrase("54", "MenuText"), $MenuRelativePath . "userlevelslist.php", 57, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}userlevels'), FALSE, FALSE, "fa fa-minus", "", FALSE);
$sideMenu->addMenuItem(53, "mi_userlevelpermissions", $MenuLanguage->MenuPhrase("53", "MenuText"), $MenuRelativePath . "userlevelpermissionslist.php", 57, "", AllowListMenu('{3C64794E-EF73-47B1-9AB0-F3ADB03E5E03}userlevelpermissions'), FALSE, FALSE, "fa fa-minus", "", FALSE);
echo $sideMenu->toScript();
?>